server:
  port: 10003
spring:
  datasource: # 数据源的相关配置
    # url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    uri: ${db.uri}
    username: ${db.username}
    password: ${db.password}
  redis:
    host: ${redis.host}
    database: ${redis.database}
    password: ${redis.password}
# 支付相关配置 配置到配置中心
#pacee1:
#  image:
#    faceLocation: E:\\pic\\foodie-image
#    serverUrl: http://localhost:8088/
#  pay:
#    returnUrl: http://raqpsv.natappfree.cc/orders/notifyMerchantOrderPaid
#    paymentUrl: http://payment.t.mukewang.com/foodie-payment/payment/createMerchantOrder
