server:
  port: 10002
spring:
  datasource: # 数据源的相关配置
    # url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    uri: ${db.uri}
    username: ${db.username}
    password: ${db.password}
  redis:
    host: ${redis.host}
    database: ${redis.database}
    password: ${redis.password}
# 照片相关配置 ，全部配置到了配置中心，所以不需要配置
#pacee1:
#  image:
#    faceLocation: /file/image/foodie/faces
#    serverUrl: http://api.enbuys.com:8088/foodie/faces/

## 开启所有actuator-endpoint，全部配置到了配置中心，所以不需要配置
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  security:
#    enabled: false