server:
  port: 10005
spring:
  datasource: # 数据源的相关配置
    # url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    uri: ${db.uri}
    username: ${db.username}
    password: ${db.password}
  redis:
    host: ${redis.host}
    database: ${redis.database}
    password: ${redis.password}
  data:
    elasticsearch:
      cluster-nodes: ${es.cluster-nodes}
      cluster-name: ${es.cluster-name}